service: correlation-ids-demo

plugins:
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  tags:
    STAGE: ${self:provider.stage}

  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'sns:Publish'
      Resource: 'arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:correlation-id-test'
    - Effect: 'Allow'
      Action:
        - 'kinesis:GetRecords'
        - 'kinesis:GetShardIterator'
        - 'kinesis:DescribeStream'
        - 'kinesis:ListStreams'
        - 'kinesis:PutRecord'
      Resource: 
        Fn::GetAtt: [Kinesis, Arn]

functions:
  api-a:
    handler: functions/api-a.handler
    environment:
      snsTopic: 'arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:correlation-id-test'
      streamName: 'correlation-id-test'
    events:
      - http:
          path: /api-a
          method: get
  
  api-b:
    handler: functions/api-b.handler
    events:
      - http:
          path: /api-b
          method: get
  
  api-c:
    handler: functions/api-c.handler
    events:
      - http:
          path: /api-c
          method: get

  sns:
    handler: functions/sns.handler
    events:
      - sns: correlation-id-test

  kinesis:
    handler: functions/kinesis.handler
    events: 
      # uncomment this section and redeploy after the stream has been created
      - stream:
          type: kinesis
          arn: 
            Fn::GetAtt: [Kinesis, Arn]
          batchSize: 10
          startingPosition: LATEST
          enabled: true

resources:
  Resources:
    Kinesis:
      Type: AWS::Kinesis::Stream
      Properties: 
        Name: correlation-id-test
        ShardCount: 1